2020-02-12 15:44:17,979 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 09:19:25,539 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 09:19:46,024 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 10:59:14,223 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:35:29,197 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:35:51,715 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:36:50,656 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:41:39,276 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:44:28,132 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:47:47,649 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:50:19,942 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:51:11,384 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:52:13,851 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:52:19,135 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 13:58:29,543 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 14:00:11,810 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 14:02:23,887 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 14:03:09,973 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 14:05:11,696 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-13 15:13:03,639 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:24:18,356 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:25:26,791 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:29:34,627 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:42:12,612 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:42:19,998 ERROR: Exception on /index [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-02-17 09:42:31,995 ERROR: Exception on /index [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-02-17 09:43:44,718 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:43:48,164 ERROR: Exception on /index [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-02-17 09:44:02,197 ERROR: Exception on /index [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-02-17 09:44:35,281 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:44:38,164 ERROR: Exception on /index [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-02-17 09:44:42,396 ERROR: Exception on /index [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-02-17 09:45:51,620 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:52:25,889 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:58:08,166 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 09:59:02,975 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 10:45:16,476 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
